# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: zaoth
description: Zaoth is a minimalist and purist image for Fedora Atomic.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - from-file: submodules/startup-setup.yml
  - from-file: submodules/repositories.yml
  - from-file: submodules/terminal-utils.yml
  - from-file: submodules/devel-utils.yml
  - from-file: submodules/desktop-apps.yml
  - from-file: submodules/devices-setup.yml
  - from-file: submodules/niri-setup.yml
  - from-file: submodules/endown-setup.yml
