include ./theme/*.st
set $font_name $font_family $font_size
include $HOME/.config/sway/theme/font
# STYLES

gaps inner              $window_gap_inner
gaps outer              $window_gap_outer
default_border pixel    $window_border_size
font pango:             $font_name
#output  * bg            $custom_wallpaper fill

# COLORS

#==================================================================================================================================================================
# class                   #border                   #background                     #text                   #indicator                  #child_border
#===================================================================================================================================================================
client.focused           $focused_border           $focused_background             $focused_text           $focused_indicator          $focused_child_border
client.focused_inactive  $focused_inative_border   $focused_inative_background     $focused_inative_text   $focused_inative_indicator  $focused_inative_child_border
client.unfocused         $unfocused_border         $unfocused_background           $unfocused_text         $unfocused_indicator        $unfocused_child_border
client.urgent            $urgent_border            $urgent_background              $urgent_text            $urgent_indicator           $urgent_child_border
