include $SWAYDIR/src/bind/modifiers.sk

# DEFAULT KEYMAP
set {
    $call_default_term              $SUPER+Shift+Return
    $call_default_files				$SUPER+Shift+Backspace
    $call_default_browser           $SUPER+Backspace

    $call_total_reload              F7
    $call_default_menu              $SUPER+Return
    $call_default_wallpaper			$SUPER+F1
}

set {
    $system_raise_volume            XF86AudioRaiseVolume
    $system_lower_volume            XF86AudioLowerVolume
    $system_mute_volume             XF86AudioMute
}

set {
    $system_display_light_raise     XF86MonBrightnessUp
    $system_display_light_lower     XF86MonBrightnessDown
}

floating_modifier $SUPER normal

set {
    $system_power_options_call      XF86PowerOff
    $system_full_lock               $SELECT+BracketRight
    $print_mode_norm                Print
    $print_mode_region              Ctrl+Print
}

#CUSTOM KEYMAP OVERRIDE
include $HOME/.config/sway/keymap/system.kb
