separator=false
separator_block_width=25
markup=pango


[time]
command=bluemoon get time --time
interval=20

[date]
command=bluemoon get time --date-ext-1
interval=3600

[wifi]
command=bluemoon get wifi --status
interval=10

[memory]
command=bluemoon get memory --perc-using
interval=5

[cpu]
command=bluemoon get cpu --usage
interval=5

[temperature]
command=bluemoon get cpu --temp
interval=5

[battery]
command=bluemoon get battery --level
interval=10
