#!/usr/bin/env bash
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=$XDG_RUNTIME_DIR/bus}"

SWAY_INIT="/tmp/sway-init.log"

#bluetheme --update --sway
#sleep 1

#if ! pgrep -x dunst >/dev/null; then
#    echo -e "\n[$(date +'%T')] Dunst not found. Starting..." >> "$SWAY_INIT"
#    killall -9 dunst 2>/dev/null
#    dunst &>/dev/null & disown
#fi

#bash $_BLUEDIR_SCRIPTS/sway-apps-compile
