name: Build Image
on:
  schedule:
    - cron: "00 00 * * 0"

  push:
    branches:
      - build

    paths-ignore:
      - "**.md"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        recipe:
          - recipe.yml
    steps:
      - uses: actions/checkout@v7

      - name: Build Custom Image
        uses: fyllus/github-action-bluebuild@v1.13
        with:
          skip_checkout: true
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.PRIVATE_KEY }}
          cosign_public_key: ${{ secrets.PUBLIC_KEY }}

          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          maximize_build_space: false
